:hardbreaks-option:
= db_xxxx: Stateflow transition appearance
Since R2020a
 
=== Usage:  MAB
=== Prerequisite: hisl_0700: Requirements linking
=== Guideline Publication: Control Algorithm Modeling Guidelines - Using MATLAB®, Simulink®, and Stateflow® 
https://github.com/WorkflowOptions/guidelines-asciidoc/blob/AddTemplate/templateA.adoc[MAB v5.0] | https://github.com/WorkflowOptions/guidelines-asciidoc/blob/AddTemplate/templateA.adoc[JMAAB v5.1] | https://github.com/WorkflowOptions/guidelines-asciidoc/blob/AddTemplate/templateA.adoc[JMAAB v6.0] 

*MATLAB Version:* All

=== Sub-ID Recommendations

NA-MAAB: a, b, c, d, e
JMAAB: a, b, c, d, e

=== Rule
Provide guideance on modeling Stateflow transitions
[cols="<1,<6"]
|===
2+s|db_xxxx: Stateflow transition appearance

|sub ID a
| Transition lines shall not cross over one another

*Custom Parameter*
Not applicable

*Rationale*
Difficult to understand the relationship between states

*Tips*
rule specific tip

*Verification*
Add link to the check

*Correct*
Correct example goes here

*Incorrect*
Incorrect example goes here


|sub ID b
| Transition lines shall not cross over other transition lines

*Custom Parameter*
Not applicable

*Rationale*
Difficult to understand the relationship between states and transition lines

*Tips*
rule specific tip

*Verification*
Add link to the check

*Correct*
Correct example goes here

*Incorrect*
Incorrect example goes here

|===

